# Customer-churn-deployment
name: MLOps CICD Pipeline

on:
  push:
    branches:
      -main

jobs:
  build-train-test-deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-py@v4
      with:
      python-version: '3.9'

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Churn Analysis
      run: python churn_analysis.py 
